idf_component_register(
    SRCS 
        "main.c"
        "modules/WIFI/wifi_lib.c"
        "modules/UART/uart_lib.c"
        "modules/TCP/tcp_lib.c"
        "modules/UDP/udp_lib.c"
    INCLUDE_DIRS 
        "."
        "modules/WIFI/"
        "modules/UART/"
        "modules/TCP/"
        "modules/UDP/"
)
