table Dim_Usuario
	lineageTag: 61721143-1341-498a-8edd-62f86e63f949

	column user_id
		dataType: int64
		formatString: 0
		lineageTag: 3dc5c452-752a-4557-9f15-959cd2553333
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column email_domain
		dataType: string
		lineageTag: 9b21ea34-6b51-4c4e-a3fc-f7e6fc4a42bf
		summarizeBy: none
		sourceColumn: email_domain

		annotation SummarizationSetBy = Automatic

	column user_prev_chargebacks
		dataType: int64
		formatString: 0
		lineageTag: 5961a210-4ecc-4093-af55-f9461448f7e9
		summarizeBy: none
		sourceColumn: user_prev_chargebacks

		annotation SummarizationSetBy = Automatic

	column user_is_high_risk
		dataType: int64
		formatString: 0
		lineageTag: a35320a1-1366-489d-b48c-09ea43c5fcbc
		summarizeBy: none
		sourceColumn: user_is_high_risk

		annotation SummarizationSetBy = Automatic

	column user_account_age_days
		dataType: int64
		formatString: 0
		lineageTag: 74b74f70-17bb-4484-8fb5-ce525492f5cf
		summarizeBy: none
		sourceColumn: user_account_age_days

		annotation SummarizationSetBy = Automatic

	partition Dim_Usuario = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\erikG\Documents\ciclo2026-1\ing_negocios\meta_2_2\uae_ecom_fraud_100k.csv"),[Delimiter=",", Columns=36, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"transaction_id", Int64.Type}, {"user_id", Int64.Type}, {"timestamp_utc", type datetime}, {"amount_aed", type number}, {"currency", type text}, {"payment_method", type text}, {"device_type", type text}, {"browser", type text}, {"merchant_category", type text}, {"items_count", Int64.Type}, {"avg_item_price", type number}, {"shipping_city", type text}, {"billing_city", type text}, {"shipping_billing_match", Int64.Type}, {"ip_address", type text}, {"ip_risk_score", type number}, {"card_present", Int64.Type}, {"bin_country", type text}, {"card_age_days", Int64.Type}, {"card_country_match", Int64.Type}, {"email_domain", type text}, {"user_prev_chargebacks", Int64.Type}, {"user_is_high_risk", Int64.Type}, {"user_account_age_days", Int64.Type}, {"transactions_last_24h", Int64.Type}, {"transactions_last_1h", Int64.Type}, {"local_hour", Int64.Type}, {"odd_hour", Int64.Type}, {"is_fraud", Int64.Type}, {"fraud_flag_ip", Int64.Type}, {"fraud_flag_mismatch", Int64.Type}, {"fraud_flag_velocity", Int64.Type}, {"fraud_flag_new_account", Int64.Type}, {"fraud_flag_prev_cb", Int64.Type}, {"fraud_flag_odd_hour", Int64.Type}, {"data_source", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"timestamp_utc", "transaction_id", "amount_aed", "currency", "payment_method", "device_type", "browser", "merchant_category", "items_count", "avg_item_price", "shipping_city", "billing_city", "shipping_billing_match", "ip_address", "ip_risk_score", "card_present", "bin_country", "card_age_days", "card_country_match", "transactions_last_24h", "transactions_last_1h", "local_hour", "odd_hour", "is_fraud", "fraud_flag_ip", "fraud_flag_mismatch", "fraud_flag_velocity", "fraud_flag_new_account", "fraud_flag_prev_cb", "fraud_flag_odd_hour", "data_source"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns", {"user_id"}),
				    #"Removed Duplicates1" = Table.Distinct(#"Removed Duplicates", {"user_id"})
				in
				    #"Removed Duplicates1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

